before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'

  binary: '{{ .ProjectName }}'
  main: cmd/notify/notify.go

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256

snapcrafts:
  - id: notify
    replacements:
      darwin: macOS
    name: notify
    publish: false
    summary: Notify is a Go-based assistance package that enables you to stream the output of several tools.
    description: |
      Notify is a Go-based assistance package that enables you to stream the output of several tools (or read from a file) and publish it to a variety of supported platforms.
    grade: stable
    confinement: strict
    license: MIT
    base: core18
    apps:
      notify:
        command: notify
        plugs:
          - home
          - network
          - removable-media
          - dot-notify
    plugs:
      dot-notify:
        interface: personal-files
        write:
          - $HOME/.config/notify