discord:
  - id: "disocord-integration-test"
    discord_webhook_url: "${DISCORD_WEBHOOK_URL}"
    discord_format: "{{data}}" 
slack:
  - id: "slack-integration-test"
    slack_channel: "random"
    slack_username: "test"
    slack_webhook_url: "${SLACK_WEBHOOK_URL}"
    slack_format: "{{data}}" 
telegram:
  - id: "telegram-integration-test"
    telegram_api_key: "${telegram_api_key}"
    telegram_chat_id: "${telegram_chat_id}"
    telegram_format: "{{data}}"
custom:
  - id: "custom-integration-test"
    custom_webhook_url: "${CUSTOM_WEBHOOK_URL}"
    custom_method: POST
    custom_format: '{{data}}'
    custom_headers: 
      Content-Type: application/json
pushover:
  - id: "push"
    pushover_user_key: "${pushover_user_key}"
    pushover_api_token: "${pushover_api_token}"
    pushover_format: "{{data}}"
    pushover_devices:
      - "iphone"
smtp:
  - id: email
    smtp_server: "${smtp_server}"
    smtp_username: "${smtp_username}"
    smtp_password: "${smtp_password}"
    from_address: "${smtp_from_address}"
    smtp_cc:
      - "${smtp_cc}"
    smtp_format: "{{data}}"
teams:
  - id: teams-integration-test
    teams_webhook_url: "${teams_webhook_url}"
    teams_format: "{{data}}"
gotify:
  - id: "gotify"
    gotify_host: "localhost"
    gotify_port: "80"
    gotify_token: "${GOTIFY_APP_TOKEN}"
    gotify_format: "{{data}}"
    gotify_disabletls: true
